compute_instance_name   = "test-instance"
compute_instance_type   = "e2-micro"
network_zone            = "us-central1-a"
source_image            = "packer-1605866625"
subnetwork_name         = ""
project_id              = ""
project_id_subnet       = ""
